network_params:
  seconds_per_slot: 2 # 2 seconds are the minimum for testing
  genesis_delay: 0 # Apparently it seems needed to avoid timestamp issues on Helix
tx_spammer_params:
  tx_spammer_extra_args: ["--slot-time=1", "--accounts=10", "--txcount=1"]

additional_services:
  - broadcaster
  - tx_spammer
  - blockscout
  - dora
  - prometheus_grafana

mev_type: full

mev_params:
  mev_builder_cl_image: sigp/lighthouse:latest
  # Bolt-specific images:
  # Adding the `bolt_boost_image` will start the devnet with Bolt-Boost
  # instead of MEV-Boost by Flashbots
  bolt_boost_image: ghcr.io/chainbound/bolt-boost:$TAG
  bolt_sidecar_image: ghcr.io/chainbound/bolt-sidecar:$TAG
  helix_relay_image: ghcr.io/chainbound/helix:$TAG
  mev_relay_image: ghcr.io/chainbound/bolt-relay:$TAG
  mev_builder_image: ghcr.io/chainbound/bolt-builder:$TAG
  mev_boost_image: ghcr.io/chainbound/bolt-mev-boost:$TAG

  mev_boost_args: []
  mev_relay_api_extra_args: []
  mev_relay_housekeeper_extra_args: []
  mev_relay_website_extra_args: []
  mev_builder_extra_args: []
  mev_builder_prometheus_config:
    scrape_interval: 15s
    labels: {}
  mev_flood_image: flashbots/mev-flood
  mev_flood_extra_args: []
  mev_flood_seconds_per_bundle: 15
  custom_flood_params:
    interval_between_transactions: 1
